/**
 * claseiaw
 * IAW
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ruarteoctavio8@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileFields } from './fileFields';
import { FileFilterOrder } from './fileFilterOrder';


export interface FileFilter1 { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: FileFilterOrder;
    where?: { [key: string]: any; };
    fields?: FileFields;
}

