/**
 * claseiaw
 * IAW
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ruarteoctavio8@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserFieldsOneOf } from './userFieldsOneOf';


/**
 * @type UserFields
 * @export
 */
export type UserFields = Set<string> | UserFieldsOneOf;

